version: 1.0.{build}
image:
- Ubuntu

branches:
  only:
    # - main
    - testing

environment:
  global:
    USER: sumankhanal

build_script:
  - ps: ./build.ps1

deploy_script:
  - ps: ./deploy.ps1